### ISSUE TITLE
개인별 Table 수정

### ISSUE THREAD

**Issue by jhk0530** [shinykorea/corona-triage#10]
데이터 우선순위에 따라 테이블에서 제외 후 따로 노출

![image](https://user-images.githubusercontent.com/6457691/76041672-1cbb6e00-5f96-11ea-9e1d-86e8bedccbbc.png)

-->

![image](https://user-images.githubusercontent.com/6457691/76041881-acf9b300-5f96-11ea-8442-171b78b0c0fd.png)

**Comment by jinseob2kim** [comment]
훨씬 보기 좋으네요 ㅎㅎ

**Comment by jhk0530** [comment]
![image](https://user-images.githubusercontent.com/6457691/76137544-ac8a1680-6081-11ea-8138-6f85e78c93ca.png)
