### ISSUE TITLE
중증도 평가 기준 업데이트

### ISSUE THREAD

**Issue by jinseob2kim** [shinykorea/corona-triage#15]
아래와 같이 중증도 평가기준이 업데이트 되어 반영 필요합니다.
- 체온은 **1점: 37.5-38.0도**, 2점: **38.1-39.0도** 또는 35.1-36.0도 입니다. 

![Screenshot_20200309-110151_Hancom Office viewer](https://user-images.githubusercontent.com/33089958/76177374-5c34c500-61f7-11ea-941c-21b16f6c44b5.jpg)

**Comment by jhk0530** [comment]
- 기존에 썼던 `나이`와 `기저질병여부`는 반영하지 않음.
- `고역` -> `고열`로 수정함. (특징적 호흡곤란 4번째)
- `심한 호흡곤란이 갑자기 올 때` 와 `호흡곤란 증상이 갑자기 심해질때` 는 하나로 합침.
- `산소포화도` 93~94%는 커버되지 않아서 2점으로 처리함. (oxygen > 93, oxygen <=95)
- `미칠 것 같은 두려움`와 `죽을 것 같은 공포` 는 하나로 합침.
- `심각한 불안`은 2점과 3점이 동일해서 모두 3점으로 처리함. 
- 최종 점수는 `체온` , `심폐기능`, `의식수준`, `심리상태`중 최대치로 0 ~ 3점을 갖게 설정.

이렇게 작업 하면 될까요? @jinseob2kim

**Comment by jinseob2kim** [comment]
단톡방에도 공유한 아래 내용이 최신 업데이트 입니다. 금요일까지 변동사항 지켜보고 진행하면 좋겠습니다. @jhk0530 
![1583821600473](https://user-images.githubusercontent.com/33089958/76285688-b317c880-62e3-11ea-9c4e-2d124967d191.png)
