### ISSUE TITLE
Summary 추가; Tile 색상으로 구분 가능하게

### ISSUE THREAD

**Issue by YoungjunNa** [shinykorea/corona-triage#17]
개선 제안사항입니다~

1.  전체적인 중증환자수/성비분포(또는 고령자 수)/최종자료업데이트 시간 등을 한번에 보여줄 수 있으면 좋을 것 같습니다. 예를들어 value box나 info box 같은 것들입니다.
2. Tile 색상이 Column에 상관없이 보라색 계열로 비슷한데 각 특성에 맞는 색을 부여해 직관성을 높히면 것이 좋을 것 같습니다(highcharter output 색과도 맞추면 좋지 않을까 싶네요). 
3. chart에 중증도 기준을 초과한 경우 color나 size로 표현을 해주는 것도 좋을 것 같습니다.

**Comment by jhk0530** [comment]
![image](https://user-images.githubusercontent.com/6457691/76676449-fe451a80-6606-11ea-9e66-6b2662e46b9f.png)

- infobox 비슷한 걸 만들어서 추가 했습니다. 필요에 따라 개수는 조절 할 수 있습니다.

2번과, 3번 같은 경우 테이블 ui가 깨지는 문제가 있어서 글자 사이즈로 조절하는건 어려울 것 같습니다. 대신 색상으로는 조절할 수가 있는데요. 

- 최중증 (3점) : 빨간색
- 중증 (2점) : 주황색
- 경증 (1점) : 노란색

으로 점수를 강조 했습니다.

데이터가 아직 확실하게 정해지지 않아서,
`자가` 탭이랑 아래 환자 별 테이블엔 아직 할당 하지 않았습니다.
