### ISSUE TITLE
환자 직접 설문 문항 선택

### ISSUE THREAD

**Issue by takos1026** [shinykorea/corona-triage#20]
구글시트로 환자가 직접 설문에 답을 하는 방식인데 이런 경우
산소포화도, 맥박수, 혈압 등 의료인만 정확한 응답을 할 수 있는 문항 처리 방법은?

**Comment by jinseob2kim** [comment]
일단은 심플하게 숫자입력으로 만들고, 피드백 받는것이 좋겠습니다.

**Comment by jhk0530** [comment]
알 수 없음 이라는 선택지를 허용 하고, 해당 값이 오는 경우 NULL 이나 NA로 처리하면 될 것 같습니다.

**Comment by takos1026** [comment]
일단 작성자를 고려하지 않고 숫자로 입력 하도록 만들었습니다.
https://forms.gle/T9hyjmJY7euhrYrS8

**Comment by jinseob2kim** [comment]
@takos1026  설문 확인했습니다. 이걸로 만들어진 구글시트 링크와 데이터 예시를 만들어주시면 좋겠습니다. 

@jhk0530 구글시트 링크 받으시면 웹에 탭 추가하여 똑같이 보여주면 좋겠습니다

**Comment by jinseob2kim** [comment]
@takos1026 설문에 단위설명이 필요합니다.

수축기 혈압을 입력해주세요 (mmHg)
1분당 맥박수를 입력해주세요.(단위: 회)
1분당 호흡 횟수를 입력해주세요.(단위: 회)
